---
title: "STA248H1: Statistics for Computer Scientists Syllabus"
author: "Course Instructor: Wei Q. Deng (wei.deng@mail.utoronto.ca)"
---

### Course Description

A survey of statistical methodology with emphasis on data analysis and applications. The topics covered include descriptive statistics, data collection and the design of experiments, univariate and multivariate design, tests of significance and confidence intervals, concept of power, multiple regression. Students learn to use a statistical computer package as part of the course (Note: STA248H1 does not count as a distribution requirement course).


### Programming languages

Both **R** and **Python** are acceptable computing languages in this course, we will see use of both throughout the course. Make sure you master at least one of them by end of this course. You will complete at least two of the specified DataCamp Programming modules as part of this course.


### Course Website

Everything you need for the course is hosted at \url{https://weiakanedeng.github.io/STA248_UT2018Summer}. Please check frequently for posting of lecture slides, practice problems and test information.


### Textbook and learning resources

There is no official textbook for this course, but if you wish to have additional books/materials to look at, I suggest the following (should be available through U of T library either as a physical copy or electronically).

 \begin{itemize}
        \item {\it Open Intro Statistics}, 3rd edition url{https://www.openintro.org/stat/textbook.php}
          \begin{itemize}
            \item Chapter 2-3 can be used as review for STA247
            \item topics in Chapter 1,4,5,7 and some of 8 are covered in this course
          \end{itemize}
        \item {\it Probability and Statistics for Engineers and Scientists} by Raymond Myers and Ronald Walpole
        \item or any other introductory statistics book.
\end{itemize}
    

### Getting help 

Please see website for schedule of office hours. Also, it is not a bad idea to google - and learning to use it effectively will become one of your most valuable skills in your future study/work.

Note that we will have additional office hours before midterm and final exam. If you wish to meet/discussion outside of office hours please schedule with me at least one day in advance.

**IMPORTANT**: please include in the subject head the course code ``STA248'' whenever you are emailing regarding this course.


### Evaluation

* Completion of two R/Python programming modules 10\% (5\% each)
* Midterm 40\%
* Final Exam 50\%
