---
title: "Welcome to STA248H1 - Statistics for Computer Scientists"
---

**You can find up to date information here. Please check regularly for new items**

Syllabus has been updated to the current schedule.


### Course Instructor: 
+ [Wei Q. Deng](wei.deng@mail.utoronto.ca)
+ Office hours: Monday 4-6pm, Wednesday 4-6pm (from second week)
+ Office hour location: SS623B (TA office in the basement of Sidney Smith - starting July 9th)
+ **Extra office hour before midterm Monday July 23rd 12:00pm-5:00pm (SS623B)**


### Class schedule
+ Monday 18:00-21:00 in SS 2118 (no lecture on Monday, August 6 (Civic holiday)
+ Wednesday 18:00-21:00 in SS 2118.

### Midterm date
+ Date: **July 23rd** 
+ Duration: 18:00-21:00
+ Location: **EX300 and EX310**
+ Due to the high demand for it, [here](https://weiakanedeng.github.io/STA248_UT2018Summer/formula_page.pdf) is the first page and last a few pages of the midterm (a.k.a ``formula'' pages).

    - I would like to emphasize again, there is really no formula in this course. I had offered to everyone who was in class that if you felt the need for something to be included on the information sheet, you can email me to have it added. And I had received only one such request, which I have included. 
    - If you want information (no concept nor definitions) included on the final exam information sheet, please email me between July 24th (after midterm) and July 28th, and I will try to accomodate.  


### Lecture Slides


+ [lecture 5](https://weiakanedeng.github.io/STA248_UT2018Summer/Lecture5_sol.pdf) contains a quick review of topics learnt so far and partial solution to some of the questions.

+ [lecture 4](https://weiakanedeng.github.io/STA248_UT2018Summer/Lecture4.pdf) and rmarkdown document to generate the slides can be found [here](https://weiakanedeng.github.io/STA248_UT2018Summer/Lecture4.Rmd) for you to look at the R/Python code chunks. **There was a typo on slide page 32 for the two-sided test p-value, which has been corrected so it is now consistent with slide page 35.** 

    - Relevant readings from OpenIntro are Chapters 4 and 5; alternatively you can look at Chapters 7, 8, 9 of *Probability and Statistics for Engineering and the Sciences*.

    
+ [lecture 3](https://weiakanedeng.github.io/STA248_UT2018Summer/Lecture3.pdf) and rmarkdown document to generate the slides can be found [here](https://weiakanedeng.github.io/STA248_UT2018Summer/Lecture3.Rmd) for you to look at the R/Python code chunks. 

    - Relevant readings from OpenIntro are Chapter 4, specifically 4.1-4.3, and 4.5; alternatively you can look at Chapters 7, 8, 9 of *Probability and Statistics for Engineering and the Sciences*.


+ [lecture 2](https://weiakanedeng.github.io/STA248_UT2018Summer/Lecture2.pdf) and rmarkdown document to generate the slides can be found [here](https://weiakanedeng.github.io/STA248_UT2018Summer/Lecture2.Rmd) for you to look at the R/Python code chunks. 

    - To practice what you learnt, make sure you know each of the concepts introduced as well as being able to solve the examples and exercises on the lecture slides. 
    - Relevant readings from *OpenIntro* are Chapters 2, 3 (review for STA247) and 4.4; alternatively you can look at Chapters 2-4 (review for ST247) and Chapters 5 and 6 of *Probability and Statistics for Engineering and the Sciences*.
    - You can also refer to your slides or textbook from STA247 if you need a refresher on concepts such as expectation, variance and moment generating functions.
    
    
    
+ [lecture 1](https://weiakanedeng.github.io/STA248_UT2018Summer/lec1.pdf) and rmarkdown document to generate the slides can be found [here](https://weiakanedeng.github.io/STA248_UT2018Summer/lec1.Rmd) for you to look at the code chunks **slide page 40 has been updated to reflect a more accurate depiction of a left skewed distribution**. 

    - To practice what you learnt in Lecture 1, you can explore the car [dataset](https://weiakanedeng.github.io/STA248_UT2018Summer/Cars93.csv) (data description [here](https://stat.ethz.ch/R-manual/R-devel/library/MASS/html/Cars93.html)). For each variable, generate what you think is the best graphical and numerical summaries. You should be able to defend your choices using the material from the lecture slides.
    - Relevant reading material from the *OpenIntro* Chapter 1; alternatively you can look at Chapter 1 of *Probability and Statistics for Engineering and the Sciences*.


### R and Python programming resources

+ R

    - [R cookbook](http://www.cookbook-r.com)
    - [R intro from Cran](https://cran.r-project.org/doc/manuals/R-intro.pdf)
    - [Quick R](https://www.statmethods.net/index.html)

+ Python

    - [statistical analyses](http://scikit-learn.org/stable/auto_examples/index.html)
    - [pydataframe](https://code.google.com/archive/p/pydataframe/)
    - [NumPy](http://scipy.org/Cookbook) and [Scipy](http://www.scipy-lectures.org)


### DataCamp 

You can take a look at [DataCamp](https://www.datacamp.com). The invitation link has been sent out, if you have not received, please let me know. 

For students using R, you should complete one of the intro stats modules and one data visualization modules:

+ Intro to Statistics with R: Analysis of Variance (ANOVA)
+ Intro to Statistics with R: Student's T-test
+ Data Visualization with ggplot2 (Part 1)
+ Data Visualization with ggplot2 (Part 2)

For students using Python, you should complete one of the intro stats modules and one data visualization modules:

+ Statistical Thinking in Python (Part 2)
+ Introduction to Data Visualization with Python

I have added additional modules that you might find helpful to get you started, but you will not be marked based on those. 

The deadline for the completion of two modules is set for **August 5th**.


